import type { IVehicle } from '../../types/vehicles.types.js'

export const vehicles: Omit<
  IVehicle,
  'id' | 'createdBy' | 'updatedBy' | 'createdAt' | 'updatedAt'
>[] = [
  { make: 'Ford', model: 'EcoSport', year: 2013, status: 'SERVICIO' },
  { make: 'Jeep', model: 'Grand Cherokee', year: 2022, status: 'SERVICIO' },
  { make: 'Toyota', model: 'Hilux', year: 2023, status: 'SERVICIO' },
  { make: 'Ford', model: 'EcoSport', year: 2014, status: 'MANTENIMIENTO' },
  { make: 'Chery', model: 'Arauca', year: 2016, status: 'SERVICIO' },
  { make: 'Chery', model: 'Tiuna X5', year: 2025, status: 'DISPONIBLE' },
  { make: 'Chevrolet', model: 'Captiva', year: 2008, status: 'DISPONIBLE' },
  { make: 'Fiat', model: 'Fiorino', year: 2015, status: 'DISPONIBLE' },
  { make: 'Toyota', model: 'Camry', year: 2022, status: 'MANTENIMIENTO' },
  { make: 'Ford', model: 'Mustang', year: 2023, status: 'MANTENIMIENTO' },
  { make: 'Toyota', model: 'Fortuner', year: 2024, status: 'MANTENIMIENTO' },
  { make: 'Chery', model: 'Tiggo 7', year: 2024, status: 'SERVICIO' },
  { make: 'Fiat', model: 'Uno', year: 2025, status: 'SERVICIO' },
  { make: 'Hyundai', model: 'H1', year: 2023, status: 'DISPONIBLE' },
  { make: 'JAC', model: 'Arena (JS2)', year: 2025, status: 'MANTENIMIENTO' },
  { make: 'Hyundai', model: 'Elantra', year: 2008, status: 'SERVICIO' },
  { make: 'Renault', model: 'Twingo', year: 2024, status: 'DISPONIBLE' },
  { make: 'Hyundai', model: 'Grand I10', year: 2023, status: 'DISPONIBLE' },
  { make: 'JAC', model: 'JS4', year: 2026, status: 'SERVICIO' },
  { make: 'Toyota', model: '4Runner', year: 2024, status: 'DISPONIBLE' },
  { make: 'Mitsubishi', model: 'Signo', year: 2016, status: 'DISPONIBLE' },
  { make: 'Toyota', model: 'Prado', year: 2022, status: 'SERVICIO' },
  { make: 'Ford', model: 'F-150', year: 2013, status: 'DISPONIBLE' },
  { make: 'Jeep', model: 'Cherokee', year: 2022, status: 'SERVICIO' },
  { make: 'Hyundai', model: 'Palisade', year: 2023, status: 'MANTENIMIENTO' },
  { make: 'Hyundai', model: 'H1', year: 2023, status: 'MANTENIMIENTO' },
  { make: 'Fiat', model: 'Mobi', year: 2024, status: 'MANTENIMIENTO' },
  { make: 'Mitsubishi', model: 'Montero Dakar', year: 2023, status: 'DISPONIBLE' },
  { make: 'Chery', model: 'QQ', year: 2023, status: 'MANTENIMIENTO' },
  { make: 'Chevrolet', model: 'Tahoe', year: 2025, status: 'MANTENIMIENTO' },
  { make: 'Toyota', model: 'Camry', year: 2022, status: 'DISPONIBLE' },
  { make: 'Jeep', model: 'CJ7', year: 2022, status: 'SERVICIO' },
  { make: 'JAC', model: 'JS6', year: 2025, status: 'SERVICIO' },
  { make: 'JAC', model: 'JS6', year: 2026, status: 'SERVICIO' },
  { make: 'Jeep', model: 'Cherokee', year: 2024, status: 'SERVICIO' },
  { make: 'Chery', model: 'Tiggo 8', year: 2025, status: 'MANTENIMIENTO' },
  { make: 'Renault', model: 'Stepway', year: 2024, status: 'DISPONIBLE' },
  { make: 'Chevrolet', model: 'Optra', year: 2007, status: 'MANTENIMIENTO' },
  { make: 'Chevrolet', model: 'Optra', year: 2024, status: 'MANTENIMIENTO' },
  { make: 'Ford', model: 'Ranger', year: 2022, status: 'DISPONIBLE' },
  { make: 'Chevrolet', model: 'Tahoe', year: 2008, status: 'MANTENIMIENTO' },
  { make: 'Hyundai', model: 'Santa Fe', year: 2024, status: 'DISPONIBLE' },
  { make: 'Ford', model: 'Ranger', year: 2024, status: 'DISPONIBLE' },
  { make: 'JAC', model: 'JS6', year: 2025, status: 'MANTENIMIENTO' },
  { make: 'Fiat', model: 'Idea', year: 2025, status: 'SERVICIO' },
  { make: 'Mitsubishi', model: 'Lancer', year: 2016, status: 'MANTENIMIENTO' },
  { make: 'Ford', model: 'Explorer', year: 2013, status: 'SERVICIO' },
  { make: 'Ford', model: 'Fusion', year: 2023, status: 'SERVICIO' },
  { make: 'Fiat', model: 'Uno', year: 2025, status: 'MANTENIMIENTO' },
  { make: 'Toyota', model: 'Camry', year: 2022, status: 'MANTENIMIENTO' }
]
